export const dishes = [
  { name: "Beef", category: "Meat" },
  { name: "Lamb", category: "Meat" },
  { name: "Pork", category: "Meat" },
  { name: "Veal", category: "Meat" },
  { name: "Game Meat", category: "Meat" },
  { name: "Duck", category: "Meat" },
  { name: "Ham", category: "Meat" },
  { name: "Cold Cuts", category: "Meat" },
  { name: "Cured Meat", category: "Meat" },
  { name: "Poultry", category: "Poultry" },
  { name: "Chicken", category: "Poultry" },
  { name: "Rich Fish", category: "Fish & Seafood" },
  { name: "Lean Fish", category: "Fish & Seafood" },
  { name: "Shellfish", category: "Fish & Seafood" },
  { name: "Seafood", category: "Fish & Seafood" },
  { name: "Sushi", category: "Fish & Seafood" },
  { name: "Sashimi", category: "Fish & Seafood" },
  { name: "Codfish", category: "Fish & Seafood" },
  { name: "Fish", category: "Fish & Seafood" },
  { name: "Grilled", category: "Fish & Seafood" },
  { name: "Soft Cheese", category: "Cheese" },
  { name: "Hard Cheese", category: "Cheese" },
  { name: "Blue Cheese", category: "Cheese" },
  { name: "Maturated Cheese", category: "Cheese" },
  { name: "Goat Cheese", category: "Cheese" },
  { name: "Mild Cheese", category: "Cheese" },
  { name: "Medium-cured Cheese", category: "Cheese" },
  { name: "Cheese", category: "Cheese" },
  { name: "Pasta", category: "Pasta" },
  { name: "Tagliatelle", category: "Pasta" },
  { name: "Lasagna", category: "Pasta" },
  { name: "Paella", category: "Fish & Seafood" },
  { name: "Pizza", category: "Pasta" },
  { name: "Vegetarian", category: "Vegetarian & Vegan" },
  { name: "Mushrooms", category: "Vegetarian & Vegan" },
  { name: "Salad", category: "Vegetarian & Vegan" },
  { name: "Fruit", category: "Vegetarian & Vegan" },
  { name: "Tomato Dishes", category: "Vegetarian & Vegan" },
  { name: "Beans", category: "Vegetarian & Vegan" },
  { name: "Eggplant Parmigiana", category: "Vegetarian & Vegan" },
  { name: "Light Stews", category: "Vegetarian & Vegan" },
  { name: "Appetizer", category: "Appetizers & Snacks" },
  { name: "Snack", category: "Appetizers & Snacks" },
  { name: "Aperitif", category: "Appetizers & Snacks" },
  { name: "French Fries", category: "Appetizers & Snacks" },
  { name: "Baked Potato", category: "Appetizers & Snacks" },
  { name: "Cream", category: "Appetizers & Snacks" },
  { name: "Sweet Dessert", category: "Desserts" },
  { name: "Fruit Dessert", category: "Desserts" },
  { name: "Citric Dessert", category: "Desserts" },
  { name: "Cake", category: "Desserts" },
  { name: "Chocolate", category: "Desserts" },
  { name: "Cookies", category: "Desserts" },
  { name: "Chestnut", category: "Desserts" },
  { name: "Spiced Fruit Cake", category: "Desserts" },
  { name: "Dessert", category: "Desserts" },
  { name: "Soufflé", category: "Desserts" },
  { name: "Dried Fruits", category: "Desserts" },
  { name: "Spicy Food", category: "Spicy Food" },
  { name: "Curry Chicken", category: "Spicy Food" },
  { name: "Asian Food", category: "Spicy Food" },
  { name: "Yakissoba", category: "Spicy Food" },
  { name: "Barbecue", category: "Meat" },
  { name: "Roast", category: "Meat" }
];
